function entity(slug, name, entityType, homepageUrl, status = 'active', summary = '') {
  return { slug, name, entityType, status, homepageUrl, summary };
}

function source({
  sourceKey,
  entitySlug,
  name,
  officialUrl,
  endpointUrl,
  transportType,
  sourceRole,
  parserKey = transportType,
  sourceType,
  itemType = 'other',
  active = true,
  archiveOnly = false,
  required = false,
  includePaths = [],
  allowedHosts = [],
}) {
  return {
    sourceKey,
    entitySlug,
    name,
    officialUrl,
    endpointUrl,
    transportType,
    sourceRole,
    parserKey,
    sourceType: sourceType ?? (
      transportType === 'sitemap' || transportType === 'html' ? 'scraped' : 'rss_official'
    ),
    itemType,
    active,
    archiveOnly,
    required,
    verifiedAt: '2026-08-30',
    includePaths,
    allowedHosts,
  };
}

export const entities = [
  entity('openai', 'OpenAI', 'provider', 'https://openai.com'),
  entity('anthropic', 'Anthropic', 'provider', 'https://www.anthropic.com'),
  entity('google-deepmind', 'Google DeepMind', 'lab', 'https://deepmind.google'),
  entity('meta-ai', 'Meta AI', 'lab', 'https://ai.meta.com'),
  entity('xai', 'xAI', 'provider', 'https://x.ai'),
  entity('mistral-ai', 'Mistral AI', 'provider', 'https://mistral.ai'),
  entity('hugging-face', 'Hugging Face', 'provider', 'https://huggingface.co'),
  entity('deepseek', 'DeepSeek', 'provider', 'https://www.deepseek.com'),
  entity('alibaba-qwen', 'Alibaba Qwen', 'provider', 'https://qwenlm.github.io'),
  entity('amazon-ai', 'Amazon AI', 'provider', 'https://aws.amazon.com/ai/'),
  entity('nvidia-ai', 'NVIDIA AI', 'provider', 'https://www.nvidia.com/en-us/ai/'),
  entity('ibm-research', 'IBM Research', 'research_org', 'https://research.ibm.com'),
  entity('z-ai', 'Z.AI', 'provider', 'https://z.ai'),
  entity('moonshot-ai', 'Moonshot AI', 'provider', 'https://www.moonshot.ai'),
  entity('minimax', 'MiniMax', 'provider', 'https://www.minimax.io'),
  entity('tencent-hunyuan', 'Tencent Hunyuan', 'provider', 'https://hunyuan.tencent.com'),
  entity('stepfun', 'StepFun', 'provider', 'https://www.stepfun.com'),
  entity('cohere', 'Cohere', 'provider', 'https://cohere.com'),
  entity('microsoft-ai', 'Microsoft AI', 'provider', 'https://www.microsoft.ai', 'watchlist'),
  entity('ai21-labs', 'AI21 Labs', 'provider', 'https://www.ai21.com'),
  entity('stability-ai', 'Stability AI', 'provider', 'https://stability.ai'),
  entity('hermes-agent', 'Hermes Agent', 'harness', 'https://github.com/NousResearch/hermes-agent'),
  entity('openclaw', 'OpenClaw', 'harness', 'https://github.com/openclaw/openclaw'),
  entity('openhands', 'OpenHands', 'harness', 'https://github.com/OpenHands/OpenHands'),
  entity('aider', 'Aider', 'harness', 'https://github.com/Aider-AI/aider'),
  entity('cline', 'Cline', 'harness', 'https://github.com/cline/cline'),
  entity('roo-code', 'Roo Code', 'harness', 'https://github.com/RooCodeInc/Roo-Code'),
  entity('goose', 'Goose', 'harness', 'https://github.com/aaif-goose/goose'),
  entity('continue', 'Continue', 'harness', 'https://github.com/continuedev/continue'),
  entity('letta', 'Letta', 'harness', 'https://github.com/letta-ai/letta'),
  entity('codex-cli', 'Codex CLI', 'harness', 'https://github.com/openai/codex'),
  entity('claude-code', 'Claude Code', 'harness', 'https://github.com/anthropics/claude-code'),
  entity('gemini-cli', 'Gemini CLI', 'harness', 'https://github.com/google-gemini/gemini-cli'),
  entity('kimi-cli', 'Kimi CLI', 'harness', 'https://github.com/MoonshotAI/kimi-cli'),
];

export const sources = [
  source({
    sourceKey: 'openai-news',
    entitySlug: 'openai',
    name: 'OpenAI News',
    officialUrl: 'https://openai.com/news/',
    endpointUrl: 'https://openai.com/news/rss.xml',
    transportType: 'rss',
    sourceRole: 'newsroom',
    required: true,
  }),
  source({
    sourceKey: 'deepmind-blog',
    entitySlug: 'google-deepmind',
    name: 'Google DeepMind Blog',
    officialUrl: 'https://deepmind.google/discover/blog/',
    endpointUrl: 'https://deepmind.google/blog/rss.xml',
    transportType: 'rss',
    sourceRole: 'newsroom',
    required: true,
    allowedHosts: [
      '983f2f5-dot-gdm-deepmind-com-prod.appspot.com',
      'd1f9a8b-dot-gdm-deepmind-com-prod.appspot.com',
    ],
  }),
  source({
    sourceKey: 'hugging-face-blog',
    entitySlug: 'hugging-face',
    name: 'Hugging Face Blog',
    officialUrl: 'https://huggingface.co/blog',
    endpointUrl: 'https://huggingface.co/blog/feed.xml',
    transportType: 'rss',
    sourceRole: 'newsroom',
    required: true,
  }),
  source({
    sourceKey: 'deepseek-v3-releases',
    entitySlug: 'deepseek',
    name: 'DeepSeek V3 Releases',
    officialUrl: 'https://github.com/deepseek-ai/DeepSeek-V3',
    endpointUrl: 'https://github.com/deepseek-ai/DeepSeek-V3/releases.atom',
    transportType: 'atom',
    sourceRole: 'releases',
    itemType: 'model_release',
    required: true,
  }),
  source({
    sourceKey: 'deepseek-gemm-releases',
    entitySlug: 'deepseek',
    name: 'DeepGEMM Releases',
    officialUrl: 'https://github.com/deepseek-ai/DeepGEMM',
    endpointUrl: 'https://github.com/deepseek-ai/DeepGEMM/releases.atom',
    transportType: 'atom',
    sourceRole: 'releases',
    required: true,
  }),
  source({
    sourceKey: 'ibm-research',
    entitySlug: 'ibm-research',
    name: 'IBM Research',
    officialUrl: 'https://research.ibm.com/blog',
    endpointUrl: 'https://research.ibm.com/rss',
    transportType: 'rss',
    sourceRole: 'research',
    itemType: 'research',
    required: true,
  }),
  source({
    sourceKey: 'aws-machine-learning',
    entitySlug: 'amazon-ai',
    name: 'AWS Machine Learning Blog',
    officialUrl: 'https://aws.amazon.com/blogs/machine-learning/',
    endpointUrl: 'https://aws.amazon.com/blogs/machine-learning/feed/',
    transportType: 'rss',
    sourceRole: 'newsroom',
    required: true,
  }),
  source({
    sourceKey: 'amazon-science',
    entitySlug: 'amazon-ai',
    name: 'Amazon Science',
    officialUrl: 'https://www.amazon.science/',
    endpointUrl: 'https://www.amazon.science/index.rss',
    transportType: 'rss',
    sourceRole: 'research',
    itemType: 'research',
    required: true,
  }),
  source({
    sourceKey: 'nvidia-blog',
    entitySlug: 'nvidia-ai',
    name: 'NVIDIA Blog',
    officialUrl: 'https://blogs.nvidia.com/',
    endpointUrl: 'https://blogs.nvidia.com/feed/',
    transportType: 'rss',
    sourceRole: 'newsroom',
    required: true,
  }),
  source({
    sourceKey: 'nvidia-generative-ai',
    entitySlug: 'nvidia-ai',
    name: 'NVIDIA Generative AI',
    officialUrl: 'https://developer.nvidia.com/blog/tag/generative-ai/',
    endpointUrl: 'https://developer.nvidia.com/blog/category/generative-ai/feed/',
    transportType: 'atom',
    sourceRole: 'newsroom',
    required: true,
  }),
  source({
    sourceKey: 'qwen-blog',
    entitySlug: 'alibaba-qwen',
    name: 'Qwen Blog',
    officialUrl: 'https://qwenlm.github.io/blog/',
    endpointUrl: 'https://qwenlm.github.io/blog/index.xml',
    transportType: 'rss',
    sourceRole: 'newsroom',
    required: true,
  }),
  source({
    sourceKey: 'anthropic-sitemap',
    entitySlug: 'anthropic',
    name: 'Anthropic News and Research',
    officialUrl: 'https://www.anthropic.com/news',
    endpointUrl: 'https://www.anthropic.com/sitemap.xml',
    transportType: 'sitemap',
    sourceRole: 'newsroom',
    includePaths: ['/news/', '/research/'],
  }),
  source({
    sourceKey: 'meta-llama-models-releases',
    entitySlug: 'meta-ai',
    name: 'Meta Llama Models Releases',
    officialUrl: 'https://github.com/meta-llama/llama-models',
    endpointUrl: 'https://github.com/meta-llama/llama-models/releases.atom',
    transportType: 'atom',
    sourceRole: 'releases',
    itemType: 'model_release',
  }),
  source({
    sourceKey: 'xai-news-watchlist',
    entitySlug: 'xai',
    name: 'xAI News Watchlist',
    officialUrl: 'https://x.ai/news',
    endpointUrl: 'https://x.ai/news',
    transportType: 'html',
    sourceRole: 'newsroom',
    parserKey: 'html',
    active: false,
  }),
  source({
    sourceKey: 'mistral-sitemap',
    entitySlug: 'mistral-ai',
    name: 'Mistral AI News',
    officialUrl: 'https://mistral.ai/news',
    endpointUrl: 'https://mistral.ai/sitemap-index.xml',
    transportType: 'sitemap',
    sourceRole: 'newsroom',
    includePaths: ['/news/'],
  }),
  source({
    sourceKey: 'z-ai-release-notes',
    entitySlug: 'z-ai',
    name: 'Z.AI Release Notes',
    officialUrl: 'https://docs.z.ai/release-notes/new-released',
    endpointUrl: 'https://docs.z.ai/sitemap.xml',
    transportType: 'sitemap',
    sourceRole: 'changelog',
    itemType: 'model_release',
    includePaths: ['/release-notes/'],
  }),
  source({
    sourceKey: 'moonshot-kimi-code-releases',
    entitySlug: 'moonshot-ai',
    name: 'Kimi Code Releases',
    officialUrl: 'https://github.com/MoonshotAI/kimi-code',
    endpointUrl: 'https://github.com/MoonshotAI/kimi-code/releases.atom',
    transportType: 'atom',
    sourceRole: 'releases',
    itemType: 'harness_release',
  }),
  source({
    sourceKey: 'moonshot-kimi-cli-releases',
    entitySlug: 'kimi-cli',
    name: 'Kimi CLI Releases',
    officialUrl: 'https://github.com/MoonshotAI/kimi-cli',
    endpointUrl: 'https://github.com/MoonshotAI/kimi-cli/releases.atom',
    transportType: 'atom',
    sourceRole: 'releases',
    itemType: 'harness_release',
  }),
  source({
    sourceKey: 'minimax-sitemap',
    entitySlug: 'minimax',
    name: 'MiniMax News and Research',
    officialUrl: 'https://www.minimax.io/news',
    endpointUrl: 'https://www.minimax.io/sitemap.xml',
    transportType: 'sitemap',
    sourceRole: 'newsroom',
    includePaths: ['/news/', '/blog/', '/research/'],
  }),
  source({
    sourceKey: 'minimax-m2-releases',
    entitySlug: 'minimax',
    name: 'MiniMax M2 Releases',
    officialUrl: 'https://github.com/MiniMax-AI/MiniMax-M2',
    endpointUrl: 'https://github.com/MiniMax-AI/MiniMax-M2/releases.atom',
    transportType: 'atom',
    sourceRole: 'releases',
    itemType: 'model_release',
    active: false,
  }),
  source({
    sourceKey: 'tencent-hunyuan-releases',
    entitySlug: 'tencent-hunyuan',
    name: 'Tencent Hunyuan Releases',
    officialUrl: 'https://github.com/Tencent-Hunyuan/Hunyuan-A13B',
    endpointUrl: 'https://github.com/Tencent-Hunyuan/Hunyuan-A13B/releases.atom',
    transportType: 'atom',
    sourceRole: 'releases',
    itemType: 'model_release',
    active: false,
  }),
  source({
    sourceKey: 'stepfun-step3-releases',
    entitySlug: 'stepfun',
    name: 'StepFun Step 3 Releases',
    officialUrl: 'https://github.com/stepfun-ai/Step3',
    endpointUrl: 'https://github.com/stepfun-ai/Step3/releases.atom',
    transportType: 'atom',
    sourceRole: 'releases',
    itemType: 'model_release',
    active: false,
  }),
  source({
    sourceKey: 'cohere-sitemap',
    entitySlug: 'cohere',
    name: 'Cohere Blog',
    officialUrl: 'https://cohere.com/blog',
    endpointUrl: 'https://cohere.com/sitemap.xml',
    transportType: 'sitemap',
    sourceRole: 'newsroom',
    includePaths: ['/blog/'],
  }),
  source({
    sourceKey: 'ai21-sitemap',
    entitySlug: 'ai21-labs',
    name: 'AI21 News',
    officialUrl: 'https://www.ai21.com/blog',
    endpointUrl: 'https://www.ai21.com/sitemap_index.xml',
    transportType: 'sitemap',
    sourceRole: 'newsroom',
    includePaths: ['/blog/'],
  }),
  source({
    sourceKey: 'stability-sitemap',
    entitySlug: 'stability-ai',
    name: 'Stability AI News',
    officialUrl: 'https://stability.ai/news',
    endpointUrl: 'https://stability.ai/sitemap.xml',
    transportType: 'sitemap',
    sourceRole: 'newsroom',
    includePaths: ['/news-updates/'],
  }),
  source({
    sourceKey: 'microsoft-ai-sitemap',
    entitySlug: 'microsoft-ai',
    name: 'Microsoft AI Blog Watchlist',
    officialUrl: 'https://blogs.microsoft.com/ai/',
    endpointUrl: 'https://blogs.microsoft.com/sitemap_index.xml',
    transportType: 'sitemap',
    sourceRole: 'newsroom',
    active: false,
    includePaths: ['/ai/'],
  }),
  source({
    sourceKey: 'anthropic-community-archive',
    entitySlug: 'anthropic',
    name: 'Anthropic Community Feed Archive',
    officialUrl: 'https://www.anthropic.com/news',
    endpointUrl: 'https://raw.githubusercontent.com/Olshansk/rss-feeds/main/feeds/feed_anthropic.xml',
    transportType: 'rss',
    sourceRole: 'newsroom',
    sourceType: 'rss_unofficial',
    active: false,
    archiveOnly: true,
  }),
  source({
    sourceKey: 'meta-research-archive',
    entitySlug: 'meta-ai',
    name: 'Meta Research Feed Archive',
    officialUrl: 'https://research.facebook.com',
    endpointUrl: 'https://research.fb.com/feed/',
    transportType: 'rss',
    sourceRole: 'research',
    itemType: 'research',
    active: false,
    archiveOnly: true,
    allowedHosts: [
      'ai.facebook.com',
      'www.metacareers.com',
      'about.fb.com',
      'engineering.fb.com',
      'sustainability.fb.com',
    ],
  }),
  source({
    sourceKey: 'meta-techcrunch-archive',
    entitySlug: 'meta-ai',
    name: 'Meta AI TechCrunch Feed Archive',
    officialUrl: 'https://techcrunch.com/tag/meta-ai/',
    endpointUrl: 'https://techcrunch.com/tag/meta-ai/feed/',
    transportType: 'rss',
    sourceRole: 'newsroom',
    sourceType: 'rss_unofficial',
    active: false,
    archiveOnly: true,
  }),
  source({
    sourceKey: 'mistral-techcrunch-archive',
    entitySlug: 'mistral-ai',
    name: 'Mistral AI TechCrunch Feed Archive',
    officialUrl: 'https://techcrunch.com/tag/mistral-ai/',
    endpointUrl: 'https://techcrunch.com/tag/mistral-ai/feed/',
    transportType: 'rss',
    sourceRole: 'newsroom',
    sourceType: 'rss_unofficial',
    active: false,
    archiveOnly: true,
  }),
  source({
    sourceKey: 'xai-techcrunch-archive',
    entitySlug: 'xai',
    name: 'xAI TechCrunch Feed Archive',
    officialUrl: 'https://techcrunch.com/tag/xai/',
    endpointUrl: 'https://techcrunch.com/tag/xai/feed/',
    transportType: 'rss',
    sourceRole: 'newsroom',
    sourceType: 'rss_unofficial',
    active: false,
    archiveOnly: true,
  }),
  ...[
    ['hermes-agent-releases', 'hermes-agent', 'Hermes Agent Releases', 'https://github.com/NousResearch/hermes-agent', 'https://github.com/NousResearch/hermes-agent/releases.atom'],
    ['openclaw-releases', 'openclaw', 'OpenClaw Releases', 'https://github.com/openclaw/openclaw', 'https://github.com/openclaw/openclaw/releases.atom'],
    ['openhands-releases', 'openhands', 'OpenHands Releases', 'https://github.com/OpenHands/OpenHands', 'https://github.com/OpenHands/OpenHands/releases.atom'],
    ['aider-releases', 'aider', 'Aider Releases', 'https://github.com/Aider-AI/aider', 'https://github.com/Aider-AI/aider/releases.atom'],
    ['cline-releases', 'cline', 'Cline Releases', 'https://github.com/cline/cline', 'https://github.com/cline/cline/releases.atom'],
    ['roo-code-releases', 'roo-code', 'Roo Code Releases', 'https://github.com/RooCodeInc/Roo-Code', 'https://github.com/RooCodeInc/Roo-Code/releases.atom'],
    ['goose-releases', 'goose', 'Goose Releases', 'https://github.com/aaif-goose/goose', 'https://github.com/aaif-goose/goose/releases.atom'],
    ['continue-releases', 'continue', 'Continue Releases', 'https://github.com/continuedev/continue', 'https://github.com/continuedev/continue/releases.atom'],
    ['letta-releases', 'letta', 'Letta Releases', 'https://github.com/letta-ai/letta', 'https://github.com/letta-ai/letta/releases.atom'],
    ['codex-cli-releases', 'codex-cli', 'Codex CLI Releases', 'https://github.com/openai/codex', 'https://github.com/openai/codex/releases.atom'],
    ['claude-code-releases', 'claude-code', 'Claude Code Releases', 'https://github.com/anthropics/claude-code', 'https://github.com/anthropics/claude-code/releases.atom'],
    ['gemini-cli-releases', 'gemini-cli', 'Gemini CLI Releases', 'https://github.com/google-gemini/gemini-cli', 'https://github.com/google-gemini/gemini-cli/releases.atom'],
  ].map(([sourceKey, entitySlug, name, officialUrl, endpointUrl]) => source({
    sourceKey,
    entitySlug,
    name,
    officialUrl,
    endpointUrl,
    transportType: 'atom',
    sourceRole: 'releases',
    itemType: 'harness_release',
  })),
];

const entityIndex = new Map(entities.map((currentEntity) => [currentEntity.slug, currentEntity]));

export function entityBySlug(slug) {
  return entityIndex.get(slug);
}
